=== dbsupport/dbs-reports/app/src/main/resources/pl/com/dbs/reports/form-schema-1.0.0.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2013 sp1 (http://www.altova.com) by ï»¿Death Song (Death Song) -->
<!--
xmlns="http://www.dbs.com.pl/reports/1.0/form" 
targetNamespace="http://www.dbs.com.pl/reports/1.0/form" 
elementFormDefault="qualified" attributeFormDefault="unqualified"
-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="http://www.dbs.com.pl/reports/1.0/form" targetNamespace="http://www.dbs.com.pl/reports/1.0/form" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="form">
		<xs:annotation>
			<xs:documentation>Dynamic form</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="fields" type="fields" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="stop" type="xs:boolean" default="false">
				<xs:annotation>
					<xs:documentation>Stop after first error?</xs:documentation>
				</xs:annotation>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="fields">
		<xs:annotation>
			<xs:documentation>Groups fields.
Renderer tries to group them on view too.</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="field" type="field" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="field">
		<xs:annotation>
			<xs:documentation>Form's field.</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="validator" type="validator" minOccurs="0" maxOccurs="unbounded">
				<xs:annotation>
					<xs:documentation>Field validators - chain. 
Order counts.</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="option" type="field-option" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="name" type="xs:string" use="required">
			<xs:annotation>
				<xs:documentation>Input variable name (unique).</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="type" type="field-type" use="required">
			<xs:annotation>
				<xs:documentation>Type of input field.</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="label" type="xs:string">
			<xs:annotation>
				<xs:documentation>Description.</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="value" type="xs:string">
			<xs:annotation>
				<xs:documentation>Initiating value.</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="tooltip" type="xs:string">
			<xs:annotation>
				<xs:documentation>Title/placeholder.</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="format" type="xs:string">
			<xs:annotation>
				<xs:documentation>Format of input (only if rendering tag can provide, otherwise will be ignored)

http://www.malot.fr/bootstrap-datetimepicker/</xs:documentation>
			</xs:annotation>
		</xs:attribute>
	</xs:complexType>
	<xs:complexType name="field-option">
		<xs:annotation>
			<xs:documentation>Enable field value</xs:documentation>
		</xs:annotation>
		<xs:attribute name="value" type="xs:string" use="required"/>
		<xs:attribute name="label" type="xs:string"/>
	</xs:complexType>
	<xs:simpleType name="field-type">
		<xs:annotation>
			<xs:documentation>Availale fields types.</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:string">
			<xs:enumeration value="text"/>
			<xs:enumeration value="number"/>
			<xs:enumeration value="date"/>
			<xs:enumeration value="select"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:annotation/>
	<xs:complexType name="validator">
		<xs:annotation>
			<xs:documentation>A Validator (abstract)</xs:documentation>
		</xs:annotation>
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute name="type" type="validator-type" use="required">
					<xs:annotation>
						<xs:documentation>Type of validator.</xs:documentation>
					</xs:annotation>
				</xs:attribute>
				<xs:attribute name="stop" type="xs:boolean" default="false">
					<xs:annotation>
						<xs:documentation>If true and validator rises problem then stops chain processing.</xs:documentation>
					</xs:annotation>
				</xs:attribute>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
	<xs:simpleType name="validator-type">
		<xs:annotation>
			<xs:documentation>Availale validators types.</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:string">
			<xs:enumeration value="required"/>
			<xs:enumeration value="min"/>
			<xs:enumeration value="max"/>
			<xs:enumeration value="before"/>
			<xs:enumeration value="after"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:annotation/>
</xs:schema>

=== dbsupport/dbs-reports/web/src/test/resources/pl/com/dbs/reports/support/web/form/test4/form.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--Sample XML file generated by XMLSpy v2013 sp1 (http://www.altova.com)-->
<form stop="false" xsi:schemaLocation="http://www.dbs.com.pl/reports/1.0/form file:///C:/workspace/dbs-reports/app/src/main/resources/pl/com/dbs/reports/form-schema-1.0.0.xsd" xmlns="http://www.dbs.com.pl/reports/1.0/form" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<fields>
		<field type="text" name="IN_TEXT1" label="Example" value="example text">
			<validator type="required" stop="true"/>
			<validator type="min">12</validator>
			<validator type="max">24</validator>
		</field>
		<field type="number" name="IN_NUMBER1" label="Ilość" value="1">
			<validator type="required" stop="true"/>
			<validator type="min">0</validator>
			<validator type="max">10</validator>
		</field>
		<field type="date" name="IN_DATA1" label="Data od">
			<validator type="required" stop="true"/>
			<validator type="before">IN_DATA2</validator>
		</field>
		<field type="date" name="IN_DATA2" label="Data do">
			<validator type="required" stop="true"/>
			<validator type="after">IN_DATA1</validator>
			<validator type="before">now</validator>
		</field>
	</fields>
</form>

=== dbsupport/dbs-reports/app/src/test/resources/pl/com/dbs/reports/domain/builders/test/mops/form.xml
<?xml version="1.0" encoding="UTF-8"?>
<form stop="false" xsi:schemaLocation="http://www.dbs.com.pl/reports/1.0/form file:///C:/workspace/dbs-reports/app/src/main/resources/pl/com/dbs/reports/form-schema-1.0.0.xsd" xmlns="http://www.dbs.com.pl/reports/1.0/form" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<fields>
		
		<field type="select" name="IN_FIRM" label="Wybierz firme" tooltip="Wybierz firme" 
			   source="CLIENT:SELECT FIRMA FROM TOMEK.FIRMY ORDER BY FIRMA" value="AUCHAN">
		</field>
		<field type="multiselect" name="IN_LOKAL" label="Lokalizacje: " tooltip="Wybierz lokalizacje aby wygenerować osobne pliki" 
			   source="CLIENT:SELECT TRIM(LOKALIZACJA)||' '||FIRMA FROM TOMEK.LOKALIZACJE ORDER BY FIRMA, LOKALIZACJA" value="%">
		</field>
		<field type="text" name="IN_NR_EW" label="Numer ewidencyjny" tooltip="POLxxxxxxx" value="%">
			<validator type="max">10</validator>			
		</field>	
		<field type="date" name="IN_DATA_W" label="Data wypełnienia" tooltip="Data bieżąca yyyy-mm-dd" format="yyyy-mm-dd" value="now">
		</field>
		<field type="date" name="IN_ROKMIES" label="Ostatni zamknięty miesiąc listy płac" format="yyyymm" tooltip="Bieżący miesiąc RRRRMM" value="now"> 
			<validator type="required" stop="true"></validator>
		</field>
	</fields>
</form>

=== dbsupport/dbs-reports/app/src/test/resources/pl/com/dbs/reports/test/Zbiorowka PRDB/form.xml
<?xml version="1.0" encoding="UTF-8"?>
<form stop="false" xsi:schemaLocation="http://www.dbs.com.pl/reports/1.0/form file:///C:/workspace/dbs-reports/app/src/main/resources/pl/com/dbs/reports/form-schema-1.0.0.xsd" xmlns="http://www.dbs.com.pl/reports/1.0/form" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<fields>
		<field type="text" name="IN_FIRMA" label="Firma" tooltip="AUCHAN: bez POL107 i POL201; POL107, POL201" value="AUCHAN">
			<validator type="required" stop="true"></validator>
			<validator type="min">1</validator>
			<validator type="max">6</validator>
		</field>
		<field type="text" name="IN_LOK" label="Lokalizacja" tooltip="POLxxx lub %" value="%">
			<validator type="max">6</validator>
		</field>
		<field type="text" name="IN_CENPLA" label="Centrum płacowe" tooltip="xxx lub %" value="%">
			<validator type="max">3</validator>
		</field>
		<field type="text" name="IN_TOP" label="Z topami" tooltip="TAK lub NIE" value="TAK">
			<validator type="min">3</validator>
			<validator type="max">3</validator>
		</field>		
		<field type="date" name="IN_DATA" label="Lista płac" tooltip="RRRRMM" format="yyyymm">
			<validator type="required" stop="true"></validator>
		</field>
	</fields>
</form>
